name: gdex-cookbook
channels:
  - conda-forge
dependencies:
  # Python version
  - python=3.12
  # pythia infrastructure
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  # Core Data & Array Computing
  - xarray
  - dask
  - cf-units
  # File Formats & I/O
  - netcdf4
  - zarr>=3.1.6     # pin for stable version3
  - fastparquet
  - kerchunk
  # Remote & Cloud File Access
  - fsspec
  - aiohttp
  - pelicanfs=1.3.1 # pin for stability
  # Remote Data Access / Catalogs
  - siphon
  - pydap
  # Visualization
  - matplotlib
  - cartopy
  - folium
